create or replace TABLE AGS_GAME_AUDIENCE.ENHANCED.LOGS_ENHANCED (
	IP_ADDRESS VARCHAR(30),
	GAMER_NAME VARCHAR(50),
	GAME_EVENT_NAME VARCHAR(20),
	GAME_EVENT_UTC TIMESTAMP_NTZ(9),
	CITY VARCHAR(20),
	REGION VARCHAR(20),
	COUNTRY VARCHAR(20),
	GAMER_LTZ_NAME VARCHAR(20),
	GAME_EVENT_LTZ TIMESTAMP_NTZ(9),
	DOW_NAME VARCHAR(3),
	TOD_NAME VARCHAR(25)
);
